server:
  port: 8002

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris: http://192.168.6.100:9200

logging:
  level:
    tracer: trace  #打开追踪器
    org.elasticsearch: trace