server:
  port: 7001

spring:
  zipkin:
    base-url: http://192.168.6.100:9411/
    sender:
      type: web

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
