server:
  port: 8888

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  redis:
#    host: 192.168.6.100
#    password: xhj123456

#自定义线程池
app:
  thread-pool:
    core: 2
    max: 4
    queue-size: 2000
    keep-alive-time: 300