server:
  port:8001

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


#自定义线程池
app:
  thread-pool:
    core: 2
    max: 4
    queue-size: 2000
    keep-alive-time: 300